name: pacebook
description: "PaceBook — Social media app with space/futuristic design. Flutter project for Mobile Programming UTS."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.0

  # HTTP client
  dio: ^5.4.3

  # Local storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # Typography
  google_fonts: ^6.2.1

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
